
export const SUBJECTS = [
  "تَمْرِيْنُ اللُّغَةِ (Tamrin Lughoh)",
  "المُطَالَعَةُ (Mutholaah)",
  "المَحْفُوْظَاتُ (Mahfudzot)",
  "الإِمْلَاءُ (Imla)",
  "العَقِيْدَةُ (Aqidah)",
  "الحَدِيْثُ (Hadist)",
  "الفِقْهُ (Fiqih)",
  "التَّارِيْخُ الإِسْلَامِيُّ (Tarikh Islam)",
  "التَّجْوِيْدُ (Tajwid)",
  "الخَطُّ (Khot)",
  "النَّحْوُ (Nahwu)",
  "الصَّرْفُ (Shorof)",
  "الإِنْشَاءُ (Insya)",
  "التَّفْسِيْرُ (Tafsir)",
  "Grammar",
  "التَّرْبِيَةُ (Tarbiyah)",
  "عُلُوْمُ القُرْآنِ (Ulumul Quran)",
  "أُصُوْلُ الفِقْهِ (Ushul Fiqh)",
  "مُصْطَلَحُ الحَدِيْثِ (Musthalah Hadits)",
  "البَلَاغَةُ (Balaghah)",
  "التَّرْبِيَةُ الإِسْلَامِيَّةُ (Pendidikan Agama Islam)",
  "Pendidikan Pancasila",
  "Bahasa Indonesia",
  "Bahasa Inggris",
  "Matematika",
  "Matematika Tingkat Lanjut",
  "Sejarah",
  "Fisika",
  "Kimia",
  "Biologi",
  "Ekonomi",
  "Geografi",
  "Sosiologi",
  "Antropologi",
  "Penjaskes",
  "Informatika",
  "Life Skill",
  "Bahasa Sunda",
  "القُرْآنُ (Al Qur'an)",
  "التَّحْفِيْظُ (Tahfidz)",
  "اللُّغَةُ العَرَبِيَّةُ (Bahasa Arab)"
];

export const TEACHERS = [
  "Amalia Nur Fariha, S.Pd",
  "Alfi Nurfadilah",
  "Nazwa Yunita",
  "Syafon Oktavia Rahma",
  "Nadra, S.Ag",
  "Ilmi Miftahul Jannah",
  "Dinda Naafida Arifin",
  "Rizki Abdul Khotib, S.Pd.I",
  "Rismawati, S.Sos.",
  "Silmi Sabila",
  "Siti Fatimah Zahra",
  "Walda Fauziah",
  "Misbahul Khoir, S.Pd",
  "Siska Yunita Dewi",
  "Elang Agesta Perkasa, S.Ag.",
  "Annisa Siti Nabila, S.Pd",
  "Putra Nahdi Abiyyu, S.Pd. L.c.",
  "M. Fikri Amrullah",
  "Ade Ihsan Firdaus",
  "M. Fikri Al-Anshory",
  "Ahmad Fauzi Rahman",
  "M. Rifki Ripaldi",
  "Syahrul Kamal Ramadhan",
  "Muhammad Hanif Fauzi, M.Pd",
  "Toni, S.Pd.",
  "Fahru Roji Malik",
  "M. Akbar Alghifari",
  "Almaas Jhoung Asri",
  "Subhan, S.Pd",
  "Ridwan Yulianto",
  "Muhammad Zuhdi Fauzi, S.Ag",
  "Umam Habimuhtada",
  "Imam Ahmadi",
  "Asep Taruna Jaya",
  "M. Abdul Hafiz Anshory",
  "Afriza Tri Wardana",
  "Ust. Sadam Hamzah, S.H.I",
  "M. Yaqub Unang, S.Ag",
  "Ust. Rizki Abdul Khotib, S.Pd.I",
  "Ust. Mursyid Anwar, M.Pd",
  "Saleha Mufida, S.Sos, M.Han",
  "Ramli Rian, M.Pd",
  "M. Jaelani Basri, S.Pd",
  "Putra Enjelikal Falah, S.E",
  "Sopian Hadi, S.Pd.I",
  "Muhammad Yadzki",
  "Nurlela, S.Ag, M.M",
  "Endang Pandawa Agung, S.Pd",
  "M. Hasby",
  "M. Irham Al Baihaqi",
  "Ahmad Hasan Munjaji",
  "Hammad Iyad Faiji",
  "Abdul Fattah Azzam",
  "Abdul Hariz Naufal, S.Ag.",
  "Sumartin, S.Pd",
  "Khairil Fahmi, S.Pd.",
  "Damar Atma Anggoro",
  "Rizal Firdaus",
  "Dava Nur Pebrianto, S.Pd",
  "Ade Holidin, S.Ag",
  "Bayu Nirpana, S.H",
  "Tia Rahmawati, S.Pd.",
  "Ahdini Rahmatillah, S.Si., Lc.",
  "Siska Indriyani, S.Sos",
  "Noor Faiz",
  "Aini Syifa, S.S",
  "M. Alief Nugraha",
  "Ichsanul Afief, S.Sos",
  "Satria Nur Oktavianto",
  "Ahmad Satibi, S.Pd",
  "M. Wildan Maulana, S.Pd",
  "Muhammad Suhail, S.Pd.I",
  "M. Hidayatu Rusydi, S.H",
  "Ahmad Fahrudin",
  "Nailul Kunni Furoida, S.Gz",
  "Venti Rakhmawati, M.Pd",
  "Muhammad Farid, S.Pd.I",
  "Hamzah Robbani, S.Sos, Lc, M.I.Kom",
  "Ahmad Firdaus, S.Ag",
  "Fadhilah, S.Pd.I",
  "Qosim Ikhsan, S.Ag",
  "Asep Saepul Millah, M.Pd",
  "H. Asep Saepudin, M.Pd",
  "Yusuf Kurniawan, S.Ag",
  "Antoni Firdaus, M.Pd",
  "Fadillah Abidana, S.S, M.Pd",
  "Muslich Anwar, M.Pd",
  "Verrary Pratama S.E",
  "Nurlaila, S.Ag",
  "Rendi Ramadhan, S.Pd",
  "Hj. Barrirotul Choiriyah, SEI",
  "Edi Sanjaya, S.Pd",
  "Zaini Fikri, S.Pd.I",
  "Lulu Zahratunnisa, S.Pd",
  "Nurachman, M.Pd",
  "Putri Dina Oktavia, S.Pd",
  "Rizki Karomah, S.Pd",
  "Saleha Mufida, M.Han",
  "Rizki Karomah, S.Si",
  "Ir. Rahmawati, M.Pd",
  "Padlin, M.Pd",
  "Doni Subiyanto, SE",
  "Adam Hafidz, S.M",
  "Liyas Syarifudin, M.Pd",
  "Wintarsa, S.Pd.I",
  "Muhammad Rahul Sayyid",
  "Ahmad Jaenilma, S.Kom",
  "Hafidz Hidayat, S.Pd",
  "Siti Nurzulfiyah, S.Pd",
  "Didah Rosyidah, S.Pd",
  "Namin, S.Pd.I",
  "Syahroni"
];
